### ISSUE TITLE
Background effects to not work in background

### ISSUE THREAD

**Issue by tristanratz** [spasimir21/camera-processor#3]
As noted in the TODO List background effects are currently not supported. However, this functionality is quite critical for our use case.

Do you have any tips on how to implement it. As far as I understood TimeWorker.setTimeout should be utilized in CameraProcessor.schedule() and BackgroundCanvas in the Renderer.

Do you have any further tips on how to implement it.

Furthermore, when implementing an abstraction of the CameraProcessor class it is quite difficult to make use of the code, since some attributes and methods are private instead of protected.

**Comment by spasimir21** [comment]
A crude implementation hopefully shouldn't take much more than using **TimeWorker** and **OffscreenCanvas**.

If it's really urgent then I would recommend forking the library and replacing those things. However, if you could wait a day or two, I'll do my best to make a more robust implementation with some settings. I've been putting that **TODO** list off for a long time anyway so it wouldn't be a bad idea to finally do some of the things on it.

A tip I could give you if you do decide to fork it would be to make a 
```typescript
type Canvas = HTMLCanvasElement | OffscreenCanvas;
```
and a utility function to instantiate an **OffscreenCanvas** if available and a normal one if not since **OffscreenCanvas** is still kind of an experimental thing.

And I'll also make sure to look into the **private/protected** thing.

**Comment by tristanratz** [comment]
Thank you for replying so quickly.
And especially for looking into the matter and the suggestions. 

If the feature is coming to the package anyway, then we can reschedule the feature for production to not do any redundant work.

If you need any support implementing it or run into any difficulties you can come back at me.

Thank you again.

**Comment by spasimir21** [comment]
Commit: ba4f1f28d65e8eccd18e925281be8b7628b800cf

This commit should've fixed the issue. I only used TimeWorker and not OffscreenCanvas though. With some very light testing using WebRTC it seems to continue working with a minimized browser so Offscreen canvas might not be necessary. However, it's not absolutely certain that it will work in all browsers (I only tested Brave). So I won't be closing this issue yet.

I would love to hear if this fixes the issue for you, so I know if I can officially take it off the TODO list.

**Comment by tristanratz** [comment]
Thank you so much for working this out so quickly.

I conducted some light testing in chrome and set some feature flags for OffscreenCanvas, Canvas filters as well as Workers - so naturally it is now hidden in Safari but seems to work in Chrome.

But I handed it over to another team member which will conduct further testing. I will keep you updated. Thank you again.

**Comment by tristanratz** [comment]
Since we've merged the branch with the improvements we haven't had any issues with the virtual background.
Thanks for the fix
